// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: proto/store.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookStoreServiceClient is the client API for BookStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookStoreServiceClient interface {
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
}

type bookStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookStoreServiceClient(cc grpc.ClientConnInterface) BookStoreServiceClient {
	return &bookStoreServiceClient{cc}
}

func (c *bookStoreServiceClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := c.cc.Invoke(ctx, "/BookStoreService/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookStoreServiceServer is the server API for BookStoreService service.
// All implementations must embed UnimplementedBookStoreServiceServer
// for forward compatibility
type BookStoreServiceServer interface {
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
	mustEmbedUnimplementedBookStoreServiceServer()
}

// UnimplementedBookStoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookStoreServiceServer struct {
}

func (UnimplementedBookStoreServiceServer) ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}
func (UnimplementedBookStoreServiceServer) mustEmbedUnimplementedBookStoreServiceServer() {}

// UnsafeBookStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookStoreServiceServer will
// result in compilation errors.
type UnsafeBookStoreServiceServer interface {
	mustEmbedUnimplementedBookStoreServiceServer()
}

func RegisterBookStoreServiceServer(s grpc.ServiceRegistrar, srv BookStoreServiceServer) {
	s.RegisterService(&BookStoreService_ServiceDesc, srv)
}

func _BookStoreService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookStoreServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookStoreService/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookStoreServiceServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookStoreService_ServiceDesc is the grpc.ServiceDesc for BookStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BookStoreService",
	HandlerType: (*BookStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBooks",
			Handler:    _BookStoreService_ListBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/store.proto",
}
