# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hello.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/hello.proto\x1a google/protobuf/descriptor.proto:.\n\x05hello\x12\x1e.google.protobuf.MethodOptions\x18\xe8\x07 \x01(\tB<\n\x14\x63om.clementjean.testP\x01Z\"github.com/Clement-Jean/test/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.hello_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(hello)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.clementjean.testP\001Z\"github.com/Clement-Jean/test/proto'
# @@protoc_insertion_point(module_scope)
