// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/hello.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto/hello.proto</summary>
public static partial class HelloReflection {

  #region Descriptor
  /// <summary>File descriptor for proto/hello.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HelloReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFwcm90by9oZWxsby5wcm90bxogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0",
          "b3IucHJvdG86LgoFaGVsbG8SHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0",
          "aW9ucxjoByABKAlCPAoUY29tLmNsZW1lbnRqZWFuLnRlc3RQAVoiZ2l0aHVi",
          "LmNvbS9DbGVtZW50LUplYW4vdGVzdC9wcm90b2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { HelloExtensions.Hello }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of proto/hello.proto</summary>
public static partial class HelloExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, string> Hello =
    new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, string>(1000, pb::FieldCodec.ForString(8002, ""));
}


#endregion Designer generated code
