# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/world.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import hello_pb2 as proto_dot_hello__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/world.proto\x1a\x11proto/hello.proto\"\x13\n\x11HelloWorldRequest\"\x14\n\x12HelloWorldResponse2T\n\x11HelloWorldService\x12?\n\nHelloWorld\x12\x12.HelloWorldRequest\x1a\x13.HelloWorldResponse\"\x08\xc2>\x05worldB?\n\x14\x63om.clementjean.testP\x01Z\"github.com/Clement-Jean/test/proto\x80\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.world_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.clementjean.testP\001Z\"github.com/Clement-Jean/test/proto\200\001\001'
  _HELLOWORLDSERVICE.methods_by_name['HelloWorld']._options = None
  _HELLOWORLDSERVICE.methods_by_name['HelloWorld']._serialized_options = b'\302>\005world'
  _HELLOWORLDREQUEST._serialized_start=40
  _HELLOWORLDREQUEST._serialized_end=59
  _HELLOWORLDRESPONSE._serialized_start=61
  _HELLOWORLDRESPONSE._serialized_end=81
  _HELLOWORLDSERVICE._serialized_start=83
  _HELLOWORLDSERVICE._serialized_end=167
# @@protoc_insertion_point(module_scope)
